---
- name: Set json query for {{ outer_item.secret }}
  ansible.builtin.set_fact:
    json_query_token: "[?item.key=='{{ outer_item.ss_serviceaccount }}'].json.access_token | [0]"

- name: Set token for {{ outer_item.secret }}
  ansible.builtin.set_fact:
    sa_token: "{{ ss_tokens.results | json_query(json_query_token) }}"

- name: Check-in {{ outer_item.secret }} 
  ansible.builtin.uri:
    url: "{{ ss_base_url }}api/v1/secrets/{{ outer_item.secret_id }}/check-in"
    method: POST
    status_code: 200
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ sa_token }}"
  changed_when: true
  ignore_errors: true


