---
- name: Finalize path to secrets
  ansible.builtin.set_fact:
    ss_secret_path_final: "{{ ss_secret_path }}{{ secret_name }}"

- name: Fetch secrets
  ansible.builtin.set_fact:
    temp_secret: >-
      {{
          lookup(
              'community.general.tss',
              0,
              secret_path=ss_secret_path_final,
              base_url=ss_base_url,
              token=temp_token
          )
      }}
  changed_when: true
  no_log: true

- name: Set password and username facts
  ansible.builtin.set_fact:
    secret: "{{ (temp_secret['items'] | items2dict(key_name='slug', value_name='itemValue'))['password'] }}"
    username: "{{ (temp_secret['items'] | items2dict(key_name='slug', value_name='itemValue'))['username'] }}"
    secret_id: "{{ temp_secret['id'] }}"
  no_log: true
