---

#- name: Finalize path to secret for {{ outer_item.secret }}
#  ansible.builtin.set_fact:
#    ss_secret_path_final: "{{ outer_item.ss_secret_path }}{{ outer_item.secret }}"

- name: Set vars for {{ outer_item.secret }}
  ansible.builtin.set_fact:
    ss_secret_path_final: "{{ outer_item.ss_secret_path }}{{ outer_item.secret }}"
    json_query_token: "[?item.key=='{{ outer_item.ss_serviceaccount }}'].json.access_token | [0]"

- name: Set access token for {{ outer_item.secret }}
  ansible.builtin.set_fact:
    sa_token: "{{ ss_tokens.results | json_query(json_query_token) }}"

- name: Fetch secret {{ outer_item.secret }}
  ansible.builtin.set_fact:
    temp_secret: >-
      {{
          lookup(
              'community.general.tss',
              0,
              secret_path=ss_secret_path_final,
              base_url=ss_base_url,
              token=sa_token
          )
      }}
  changed_when: true

- name: Combine fetched data with list of secrets
  set_fact:
    ss_secrets_all_final: "{{ ss_secrets_all_final + [outer_item | combine(extra_items)] }}"
  run_once: true
  vars:
    extra_items:
      pw: "{{ (temp_secret['items'] | items2dict(key_name='slug', value_name='itemValue'))['password'] }}"
      username: "{{ (temp_secret['items'] | items2dict(key_name='slug', value_name='itemValue'))['username'] }}"
      secret_id: "{{ temp_secret['id'] }}"
