---

- name: Set facts
  ansible.builtin.set_fact:
    ss_base_url: "https://{{ ss_hostname }}/"
 
- name: Generate token
  ansible.builtin.uri:
#    url: "{{ hostvars[ansible_controller]['ss_base_url'] }}oauth2/token"
    url: "{{ ss_base_url }}oauth2/token"
    method: POST
    status_code: 200
    body:
      username: "{{ item.key }}"
      password: "{{ item.value.password }}"
      grant_type: "password"
    body_format: form-urlencoded
  changed_when: true
  register: ss_tokens
#  no_log: true
  loop: "{{ ss_serviceaccounts | dict2items }}"

- name: debug
  ansible.builtin.debug:
    msg: "{{ ss_tokens.results }}"

- name: Set serviceaccounts facts
  ansible.builtin.debug:
    msg: "{{ ss_tokens | json_query('results[*].json.access_token') }}"

- name: Get access token based on username | ServiceAccount
  ansible.builtin.debug:
    msg: "{{ ss_tokens.results | json_query(query) }}"
  vars:
    query: "[?item.key=='ServiceAccount'].json.access_token | [0]"

- name: Get access token based on username | ServiceAccount2
  ansible.builtin.debug:
    msg: "{{ ss_tokens.results | json_query(query) }}"
  vars:
    query: "[?item.key=='ServiceAccount2'].json.access_token | [0]"


