---

- name: Prepare variables
  ansible.builtin.set_fact:
    ss_base_url: "https://{{ ss_hostname }}/"
    ss_secrets_all_final: []

- name: Get access token
  ansible.builtin.uri:
    url: "{{ ss_base_url }}oauth2/token"
    method: POST
    status_code: 200
    body:
      username: "{{ item.key }}"
      password: "{{ item.value.password }}"
      grant_type: "password"
    body_format: form-urlencoded
  changed_when: true
  register: ss_tokens
  loop: "{{ ss_serviceaccounts | dict2items }}"

